export const sidebarMenu = [
  {
    path: "/",
    title: "Home",
    id: "home",
    isChild: false,
    icon: "HomeIcon",
    isValid: ["hr", "marketing", "t&d"],
    subMenu: [],
  },
  {
    path: "#",
    title: "Onboarding",
    icon: "OnboardingIcon",
    id: "onbording",
    isChild: true,
    isValid: ["hr", "marketing"],
    subMenu: [
      {
        title: "Template #1",
        path: "onbording/template1",
        id: "template1",
      },
      {
        title: "Template #2",
        path: "onbording/template2",
        id: "template2",
      },
      {
        title: "Template #3",
        path: "onbording/template3",
        id: "template3",
      },
      {
        title: "Template #4",
        path: "onbording/template4",
        id: "template4",
      },
      {
        title: "Template #5",
        path: "onbording/template5",
        id: "template5",
      },
      {
        title: "Template #6",
        path: "onbording/template6",
        id: "template6",
      },
      {
        title: "Template #7",
        path: "onbording/template7",
        id: "template7",
      },
      {
        title: "Template #8",
        path: "onbording/template8",
        id: "template8",
      },
      {
        title: "Template #9",
        path: "onbording/template9",
        id: "template9",
      },
    ],
  },
  // {
  //   path: "#",
  //   title: "Welcome Mailer",
  //   id: "welcomemailer",
  //   isChild: true,
  //   subMenu: [
  //     {
  //       title: "Template #1",
  //       path: "welcomemailer/template1",
  //       id: "template1",
  //     },
  //   ],
  // },
  {
    path: "/ibuddy-template",
    title: "iBuddy",
    id: "ibuddy-template",
    icon: "IBuddy",
    isChild: false,
    isValid: ["hr"],
    subMenu: [],
  },
  {
    path: "/appreciation",
    title: "Appreciation",
    id: "appreciation",
    icon: "AppreciationIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
  {
    path: "/italk",
    title: "iTalk",
    id: "italk",
    icon: "ItalkIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
  {
    path: "#",
    title: "Certification",
    id: "certification",
    icon: "CertificationIcon",
    isChild: true,
    isValid: ["t&d"],
    subMenu: [
      {
        title: "iTalk",
        path: "/certification/italk",
        id: "italk",
      },
      {
        title: "Learning1",
        path: "/certification/learning1",
        id: "learning1",
      },
      {
        title: "Learning2",
        path: "/certification/learning2",
        id: "learning2",
      },
    ],
  },
  {
    title: "iLeap",
    path: "/iLeap",
    id: "iLeap",
    icon: "IleapIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
  {
    path: "/learning-league-template",
    title: "Learning League ",
    id: "learning-league-template",
    icon: "LearningIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
  {
    path: "/wall-of-fame-template",
    title: "Wall Of Fame",
    id: "wall-of-fame-template",
    icon: "WallOfFameIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
  {
    path: "/teaser",
    title: "Teaser",
    id: "teaser",
    icon: "TeaserIcon",
    isChild: false,
    isValid: ["t&d"],
    subMenu: [],
  },
];
