version: "3"

services:
  web:
    image: onboarding-image
    container_name: onboarding-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=development
